### ISSUE TITLE
Information search

### ISSUE THREAD

**Issue by Knolaisen** [CogitoNTNU/TutorAI#75]
* All information generated by the application should reference a page in the curriculum
* Given a statement about the curriculum, the application should be able to tell whether I is supported by a uploaded source and return book title and page number.

**Comment by SverreNystad** [comment]
The information search needs to the client to give the backend:
* the name of the curriculum file
* The question from the user

The Client will receive:
* The formatet response
* List of used Pages of Page type

**Comment by SverreNystad** [comment]
All work on the backend is done for this feature. We only need to make the remaining UI in the frontend.
